export const CURRENCY = 'CURRENCY';
export const CURRENCY_SUCCESS = 'CURRENCY_SUCCESS';
export const SIMULATION = 'SIMULATION';
export const SIMULATION_SUCCESS = 'SIMULATION_SUCCESS';
export const SIMULATION_TWO_SUCCESS = 'SIMULATION_TWO_SUCCESS';
export const SIMULATION_TWO = 'SIMULATION_TWO';
export const SIMULATION_FAIL = 'SIMULATION_FAIL';
export const UPDATE_TABS = 'UPDATE_TABS';